In [1]:
import pandas as pd

In [28]:
cnv= pd.read_csv(r"cnv_ap_matrix.csv")
cnv

,filename,AARS1_CNV,AARS2_CNV,ABCB1_CNV,ABCB4_CNV,ABCC1_CNV,ABCC2_CNV,ABL1_CNV,ABL2_CNV,ABRAXAS1_CNV,...,ZFHX3_CNV,ZFP36L1_CNV,ZFPM2_CNV,ZMIZ1_CNV,ZMYM3_CNV,ZMYM4_CNV,ZMYND10_CNV,ZNF217_CNV,ZNF521_CNV,ZSWIM7_CNV
0,IN-423-UJMA,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,IN-423-VFJC,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,IN-423-VGDP,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,IN-423-VGYD,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,IN-423-VH4D,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,IN-423-XETAV,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1057,IN-423-XEYA4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1058,IN-423-XEYD5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1059,IN-423-XFCAE,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1060,IN-423-XFCAX,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [39]:
cnv_stats = cnv.sum(axis=0).reset_index().iloc[1:]
cnv_stats[['CNV', 'freq']] = cnv_stats 
cnv_stats.drop(['index', 0], axis=1, inplace=True)

In [45]:
cnv_stats.sort_values('freq', ascending=False)

              CNV freq
940      SIK1_CNV  285
697     NUDT1_CNV  238
127    CARD11_CNV  237
566    MAD1L1_CNV  236
88      AXIN1_CNV  235
...           ...  ...
322      ERI1_CNV    1
1027     TET2_CNV    1
170     CEP43_CNV    1
918    SEC31A_CNV    1
1052  TNFAIP3_CNV    1

[1151 rows x 2 columns]

In [4]:
muts = pd.read_csv("raw_data_combi.csv")
muts

,Samples,ANK3,DICER1,DIS3,MAP3K1,MYBBP1A,NOTCH2,PTPRJ,RAD54B,CDT1,...,FANCF,GAS7,RALA,DMC1,COL4A3,LIFR,MLH1,age,gender,MSI
0,IN-423-VCCA,1,1,1,1,1,1,1,1,0,...,0,0,0,0,0,0,0,61,FEMALE,13.36
1,IN-423-WC2J,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,68,MALE,11.06
2,IN-423-VK4A,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,43,MALE,10.94
3,IN-423-XA4A9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,51,FEMALE,8.34
4,IN-423-VI3E,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,52,FEMALE,11.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1221,IN-423-WBFU,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,43,MALE,13.28
1222,IN-423-VJ5R,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,63,MALE,12.99
1223,IN-423-VHRW,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,51,MALE,11.00
1224,IN-423-WAJF,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,34,MALE,13.35
1225,IN-423-WALD,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,56,FEMALE,9.21

In [6]:
combi_df = pd.merge(muts, cnv, left_on='Samples', right_on='filename', how = 'left')

In [15]:
combi_df = combi_df.fillna(0).drop('filename', axis =1)

In [23]:
combi_df.to_csv('./combi_data.csv', index = False)

In [26]:
combi_df[combi_df['EGFR_CNV'] == 1][['Samples', 'EGFR_CNV']]

           Samples  EGFR_CNV
9      IN-423-WBAI       1.0
24     IN-423-WAPA       1.0
84     IN-423-WAWP       1.0
116    IN-423-WEHB       1.0
119    IN-423-WCJI       1.0
132    IN-423-WA5D       1.0
186    IN-423-VKCH       1.0
192    IN-423-WBTE       1.0
229    IN-423-VKCG       1.0
246    IN-423-WBBD       1.0
260    IN-423-WA5C       1.0
272    IN-423-WBNK       1.0
308    IN-423-WCCA       1.0
335   IN-423-W9RAG       1.0
336    IN-423-VKWJ       1.0
378    IN-423-WCFG       1.0
380    IN-423-VKXB       1.0
425    IN-423-WC1T       1.0
502    IN-423-WBQF       1.0
564    IN-423-WBUE       1.0
572    IN-423-WCOH       1.0
581    IN-423-WEJO       1.0
618   IN-423-W9TAG       1.0
771    IN-423-WBXE       1.0
822    IN-423-W4SA       1.0
930    IN-423-WAYA       1.0
990    IN-423-VKBK       1.0
1027  IN-423-XAVAL       1.0
1103   IN-423-WASC       1.0
1107   IN-423-W4QK       1.0